devices:
  - id: "drive_avid"
    host: "10.1.206.241" 
    port: 502
    name: "PLC Principal"
    critical_parameters: 
      - "P1.00"
      - "P1.01"
      - "P1.02"
      - "P1.03"
      - "P1.04"
      - "P1.05"
      - "P1.12"
      - "P1.13"
      - "P1.14"
      - "P1.15"
      - "P1.16"
      - "P1.17"
      - "P1.18"
      - "P2.01"
      - "P2.02"
      - "P2.03"
      - "P5.00"
      - "P5.14"
      - "P5.22"
      - "P8.00"
      - "P9.04"
      - "P9.05"
      - "P9.06"
      - "P9.08"
      - "P10.00"
      - "P10.01"
      - "P10.02"
      - "P10.03"
      - "P10.04"
      - "P10.05"
      - "P10.06"
      - "P10.07"
      - "P10.08"
      - "P10.09"
      - "P10.10"
      - "P10.11"
      - "P10.12"
      - "P10.13"
      - "P10.14"
      - "P10.15"
      - "P10.16"
      - "P10.17"
      - "P10.18"
      - "P10.19"
      - "P11.00"
      - "P11.01"
      - "P11.03"
      - "P11.04"
      - "P11.05"
      - "P11.06"
      - "P11.07"
      - "P11.08"
      - "P11.09"
      - "P11.10"
      - "P11.11"
      - "P11.19"
      - "P11.20"
      - "P11.49"
      - "P11.50"

