devices:
- id: drive_avid
  host: 10.1.206.241
  port: 502
  name: PLC Principal
  parameter_file: parameters/drive.parameters.json
  critical_parameters:
  - P1.00
  - P1.01
  - P1.02
  - P1.03
  - P1.04
  - P1.05
  - P1.12
  - P1.13
  - P1.14
  - P1.15
  - P1.16
  - P1.17
  - P1.18
  - P2.01
  - P2.02
  - P2.03
  - P5.00
  - P5.01
  - P5.14
  - P5.22
  - P8.00
  - P9.03
  - P9.04
  - P9.05
  - P9.06
  - P9.08
  - P10.00
  - P10.01
  - P10.02
  - P10.10
  - P10.11
  - P10.12
  - P10.13
  - P10.14
  - P10.20
  - P10.21
  - P10.22
  - P10.23
  - P10.24
  - P10.25
  - P10.26
  - P10.27
  - P10.28
  - P10.29
  - P10.30
  - P10.31
  - P10.34
  - P11.00
  - P11.01
  - P11.03
  - P11.04
  - P11.05
  - P11.06
  - P11.07
  - P11.08
  - P11.09
  - P11.10
  - P11.11
  - P11.19
  - P11.20
  - P11.49
  - P11.50
  - P21.01
  - P45.00
  - P45.01
  - P45.02
  - P45.03
  - P45.04
  - P45.05
  - P45.06
  - P45.07
  - P45.08
  - P45.09
  - P45.10
  - P45.11
  - P45.12
  - P45.13
  - P45.14
  - P45.15
  - P45.16
  - P45.17
  - P45.18
  - P45.19
  - P45.20
  - P45.21
- id: drive_avid_motor2
  host: 10.1.206.251
  port: 502
  name: PLC Principal Motor
  parameter_file: parameters/drive.parameters.json
  critical_parameters:
  - P1.00
  - P1.01
  - P1.02
  - P1.03
  - P1.04
  - P1.05
  - P1.12
  - P1.13
  - P1.14
  - P1.15
  - P1.16
  - P1.17
  - P1.18
  - P2.01
  - P2.02
  - P2.03
  - P5.00
  - P5.01
  - P5.14
  - P5.22
  - P8.00
  - P9.03
  - P9.04
  - P9.05
  - P9.06
  - P9.08
  - P10.00
  - P10.01
  - P10.02
  - P10.10
  - P10.11
  - P10.12
  - P10.13
  - P10.14
  - P10.20
  - P10.21
  - P10.22
  - P10.23
  - P10.24
  - P10.25
  - P10.26
  - P10.27
  - P10.28
  - P10.29
  - P10.30
  - P10.31
  - P10.34
  - P11.00
  - P11.01
  - P11.03
  - P11.04
  - P11.05
  - P11.06
  - P11.07
  - P11.08
  - P11.09
  - P11.10
  - P11.11
  - P11.19
  - P11.20
  - P11.49
  - P11.50
  - P21.01
  - P45.00
  - P45.01
  - P45.02
  - P45.03
  - P45.04
  - P45.05
  - P45.06
  - P45.07
  - P45.08
  - P45.09
  - P45.10
  - P45.11
  - P45.12
  - P45.13
  - P45.14
  - P45.15
  - P45.16
  - P45.17
  - P45.18
  - P45.19
  - P45.20
  - P45.21
- id: wago
  host: 10.1.206.237
  port: 502
  unit_id: 255
  coil_write_mode: multiple
  name: Wago
  parameter_file: parameters/wago.parameters.json
  critical_parameters:
  - Remote_Speed_In
  - Auto_Speed_SP1
  - Cooling_Water_Press
  - Speed_Out_Drive
  - Analog_Test_3
  - Analog_Test_4
  - Analog_Test_5
  - Analog_Test_6
  - Analog_Test_7
  - Analog_Test_8
  - Analog_Test_9
  - Analog_Test_10
  - Temp_Winding_A1
  - Temp_Winding_B1
  - Temp_Winding_C1
  - Temp_Bearing_DE
  - Temp_Bearing_NDE
  - Analog_Test_16
  - Analog_Test_17
  - Analog_Test_18
  - Analog_Test_19
  - Drive_Cooling_Temp
  - Analog_Test_21
  - Analog_Test_22
  - Analog_Test_23
  - Analog_Test_24
  - Analog_Test_25
  - Analog_Test_26
  - Analog_Test_27
  - Analog_Test_28
  - Analog_Test_29
  - Analog_Test_30
  - Analog_Test_31
  - Analog_Test_32
  - Analog_Test_33
  - Analog_Test_34
  - Analog_Test_35
  - Analog_Test_36
  - Analog_Test_37
  - Analog_Test_38
  - Analog_Test_39
  - Analog_Test_40
  - Analog_Test_41
  - Analog_Test_42
  - Analog_Test_43
  - Analog_Test_44
  - Analog_Test_45
  - Analog_Test_46
  - Analog_Test_47
  - Analog_Test_48
  - Analog_Test_49
  - Analog_Test_50
  - Analog_Test_51
  - Analog_Test_52
  - Analog_Test_53
  - Analog_Test_54
  - Analog_Test_55
  - Analog_Test_56
  - Analog_Test_57
  - Analog_Test_58
  - Analog_Test_59
  - Analog_Test_60
  - Analog_Test_61
  - Analog_Test_62
  - Analog_Test_63
  - Analog_Test_64
  - Analog_Test_65
  - Analog_Test_66
  - Analog_Test_67
  - Analog_Test_68
  - Analog_Test_69
  - Analog_Test_70
  - Analog_Test_71
  - Analog_Test_72
  - Analog_Test_73
  - Analog_Test_74
  - Analog_Test_75
  - Analog_Test_76
  - Analog_Test_77
  - Analog_Test_78
  - Analog_Test_79
  - Analog_Test_80
  - Analog_Test_81
  - Analog_Test_82
  - Analog_Test_83
  - Analog_Test_84
  - Analog_Test_85
  - Analog_Test_86
  - Analog_Test_87
  - Analog_Test_88
  - Analog_Test_89
  - Analog_Test_90
  - Analog_Test_91
  - Analog_Test_92
  - Analog_Test_93
  - Analog_Test_94
  - Analog_Test_95
  - Analog_Test_96
  - Analog_Test_97
  - Analog_Test_98
  - Analog_Test_99
  - Analog_Test_100
  - Motor_Winding_A1_DEGF
  - Motor_Winding_B1_DEGF
  - Motor_Winding_C1_DEGF
  - Motor_Winding_A2_DEGF
  - Motor_Winding_B2_DEGF
  - Motor_Winding_C2_DEGF
  - Motor_Bearing_DE_DEGF
  - Motor_Bearing_NDE_DEGF
  - Motor_Winding_A1_Spare_DEGF
  - Motor_Winding_B1_Spare_DEGF
  - Motor_Winding_C1_Spare_DEGF
  - Motor_Winding_A2_Spare_DEGF
  - Motor_Winding_B2_Spare_DEGF
  - Motor_Winding_C2_Spare_DEGF
  - Motor_Bearing_DE_Spare_DEGF
  - Motor_Bearing_NDE_Spare_DEGF
  - Coolant_Temp_DEGF
  - Coolant_Pressure_PSI
  - RB_Local_Control
  - RB_Remote_Control
  - RB_Breaker_Close
  - RB_Breaker_Open
  - RB_Estop_Status
  - Supply_480VAC_On
  - Drive_Coolant_Flow_Sw
  - Drive_Coolant_Pressure_Sw
  - Drive_Coolant Leak_Sw
  - Drive_Coolant_Pump_Sw
  - Drive_Coolant_Pump2_Running
  - Drive_Coolant_Pump1_Running
  - Drive_Cooland Pump_Auto
  - RB_Drive_OK
  - RB_Drive_Running
  - RB_Precharge_OK
  - Coolant_Pump1_Run
  - Trans_Cooling_Start
  - Motor_Heater_Ctrl
  - RB_Estop_Reset
  - RB_Blower_Start
  - RB_Main_Brk_Close
  - RB_Main_Brk_Open
  - RB_Drive_Start
  - RB_Drive_Reset
  - Main_CB_Closed_Light
  - Coolant_Pump2_Run
- id: wago_motor2
  host: 10.1.206.247
  port: 502
  unit_id: 255
  coil_write_mode: multiple
  name: Wago Motor
  parameter_file: parameters/wago.parameters.json
  critical_parameters:
  - Remote_Speed_In
  - Auto_Speed_SP1
  - Cooling_Water_Press
  - Speed_Out_Drive
  - Analog_Test_3
  - Analog_Test_4
  - Analog_Test_5
  - Analog_Test_6
  - Analog_Test_7
  - Analog_Test_8
  - Analog_Test_9
  - Analog_Test_10
  - Temp_Winding_A1
  - Temp_Winding_B1
  - Temp_Winding_C1
  - Temp_Bearing_DE
  - Temp_Bearing_NDE
  - Analog_Test_16
  - Analog_Test_17
  - Analog_Test_18
  - Analog_Test_19
  - Drive_Cooling_Temp
  - Analog_Test_21
  - Analog_Test_22
  - Analog_Test_23
  - Analog_Test_24
  - Analog_Test_25
  - Analog_Test_26
  - Analog_Test_27
  - Analog_Test_28
  - Analog_Test_29
  - Analog_Test_30
  - Analog_Test_31
  - Analog_Test_32
  - Analog_Test_33
  - Analog_Test_34
  - Analog_Test_35
  - Analog_Test_36
  - Analog_Test_37
  - Analog_Test_38
  - Analog_Test_39
  - Analog_Test_40
  - Analog_Test_41
  - Analog_Test_42
  - Analog_Test_43
  - Analog_Test_44
  - Analog_Test_45
  - Analog_Test_46
  - Analog_Test_47
  - Analog_Test_48
  - Analog_Test_49
  - Analog_Test_50
  - Analog_Test_51
  - Analog_Test_52
  - Analog_Test_53
  - Analog_Test_54
  - Analog_Test_55
  - Analog_Test_56
  - Analog_Test_57
  - Analog_Test_58
  - Analog_Test_59
  - Analog_Test_60
  - Analog_Test_61
  - Analog_Test_62
  - Analog_Test_63
  - Analog_Test_64
  - Analog_Test_65
  - Analog_Test_66
  - Analog_Test_67
  - Analog_Test_68
  - Analog_Test_69
  - Analog_Test_70
  - Analog_Test_71
  - Analog_Test_72
  - Analog_Test_73
  - Analog_Test_74
  - Analog_Test_75
  - Analog_Test_76
  - Analog_Test_77
  - Analog_Test_78
  - Analog_Test_79
  - Analog_Test_80
  - Analog_Test_81
  - Analog_Test_82
  - Analog_Test_83
  - Analog_Test_84
  - Analog_Test_85
  - Analog_Test_86
  - Analog_Test_87
  - Analog_Test_88
  - Analog_Test_89
  - Analog_Test_90
  - Analog_Test_91
  - Analog_Test_92
  - Analog_Test_93
  - Analog_Test_94
  - Analog_Test_95
  - Analog_Test_96
  - Analog_Test_97
  - Analog_Test_98
  - Analog_Test_99
  - Analog_Test_100
  - Motor_Winding_A1_DEGF
  - Motor_Winding_B1_DEGF
  - Motor_Winding_C1_DEGF
  - Motor_Winding_A2_DEGF
  - Motor_Winding_B2_DEGF
  - Motor_Winding_C2_DEGF
  - Motor_Bearing_DE_DEGF
  - Motor_Bearing_NDE_DEGF
  - Motor_Winding_A1_Spare_DEGF
  - Motor_Winding_B1_Spare_DEGF
  - Motor_Winding_C1_Spare_DEGF
  - Motor_Winding_A2_Spare_DEGF
  - Motor_Winding_B2_Spare_DEGF
  - Motor_Winding_C2_Spare_DEGF
  - Motor_Bearing_DE_Spare_DEGF
  - Motor_Bearing_NDE_Spare_DEGF
  - Coolant_Temp_DEGF
  - Coolant_Pressure_PSI
  - RB_Local_Control
  - RB_Remote_Control
  - RB_Breaker_Close
  - RB_Breaker_Open
  - RB_Estop_Status
  - Supply_480VAC_On
  - Drive_Coolant_Flow_Sw
  - Drive_Coolant_Pressure_Sw
  - Drive_Coolant Leak_Sw
  - Drive_Coolant_Pump_Sw
  - Drive_Coolant_Pump2_Running
  - Drive_Coolant_Pump1_Running
  - Drive_Cooland Pump_Auto
  - RB_Drive_OK
  - RB_Drive_Running
  - RB_Precharge_OK
  - Coolant_Pump1_Run
  - Trans_Cooling_Start
  - Motor_Heater_Ctrl
  - RB_Estop_Reset
  - RB_Blower_Start
  - RB_Main_Brk_Close
  - RB_Main_Brk_Open
  - RB_Drive_Start
  - RB_Drive_Reset
  - Main_CB_Closed_Light
  - Coolant_Pump2_Run
- id: wago_live_motor1
  host: 10.1.206.239
  port: 502
  unit_id: 255
  coil_write_mode: multiple
  name: WAGO Live Motor
  parameter_file: parameters/cooling_plc_motor1.parameters.json
  critical_parameters:
  - CoolPump1_HMI_Stop
  - CoolPump1_HMI_Start
  - CoolPump2_HMI_Stop
  - CoolPump2_HMI_Start
  - CoolSys_OK
  - Coolant_Pump1_Run
  - Coolant_Pump2_Run
  - Coolant_Temp_DEGF
  - Coolant_Pressure_PSI
  - Drive_Coolant_Pump2_Running
  - Drive_Coolant_Pump1_Running
  - Drive_Coolant_Flow_Sw
  - Drive_Coolant Leak_Sw
- id: wago_live_motor2
  host: 10.1.206.249
  port: 502
  unit_id: 255
  coil_write_mode: multiple
  name: WAGO Live Motor
  parameter_file: parameters/cooling_plc_motor2.parameters.json
  critical_parameters:
  - CoolPump1_HMI_Stop
  - CoolPump1_HMI_Start
  - CoolPump2_HMI_Stop
  - CoolPump2_HMI_Start
  - CoolSys_OK
  - Coolant_Pump1_Run
  - Coolant_Pump2_Run
  - Coolant_Temp_DEGF
  - Coolant_Pressure_PSI
  - Drive_Coolant_Pump2_Running
  - Drive_Coolant_Pump1_Running
  - Drive_Coolant_Flow_Sw
  - Drive_Coolant Leak_Sw
